name: Mark Packages as Broken
on:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: cf
        environment-file: environment.yml
        auto-activate-base: true
    - name: Mark packages as broken
      shell: bash -l {0}
      run: |
          conda activate cf
          git config --global user.name "conda-forge-admin"
          git config --global user.email "pelson.pub+conda-forge@gmail.com"
          python mark_broken.py mark
      env:
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.CF_GITHUB_TOKEN }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
